"""Guard the ORM models against drifting from the real schema.

The v3 models are generated by reflecting the database, and `alembic autogenerate`
is deliberately not used -- the migrations are hand-written SQL because partitioned
parents, owner-executed persona views and per-role grants have no
declarative form. That combination buys correctness at the cost of one risk: a
migration can change the schema and leave the models stale, and nothing would say
so until some rarely-used column raised UndefinedColumn at runtime.

This test closes that gap. Run it after any schema migration; if it fails,
regenerate:

    python scripts/generate_orm_models.py

Requires a live database. Skips (does not fail) when one is unreachable, so it
does not break a unit-test run on a machine with no Postgres.
"""
from __future__ import annotations

import re

import pytest
import sqlalchemy as sa

from app.core import settings
from app.models.schemas import Base
from app.models.schemas import v3_core, v3_meta

# Partition children share their parent's shape; mapping them would mean 160
# redundant classes.
_PARTITION_CHILD = re.compile(r"_p(?:\d{6}|default)$")

SCHEMAS = {
    settings.ci_core_schema: v3_core,
    settings.ci_meta_schema: v3_meta,
}


def _engine():
    url = settings.postgres_uri.replace("postgresql://", "postgresql+psycopg://", 1)
    try:
        engine = sa.create_engine(url, connect_args={"connect_timeout": 3})
        with engine.connect():
            pass
        return engine
    except Exception as exc:  # noqa: BLE001
        pytest.skip(f"no database reachable for drift check: {exc}")


def _mapped_tables(schema: str) -> dict[str, sa.Table]:
    return {
        table.name: table
        for table in Base.metadata.tables.values()
        if table.schema == schema
    }


def _live_tables(insp, schema: str) -> list[str]:
    return sorted(
        t for t in insp.get_table_names(schema=schema) if not _PARTITION_CHILD.search(t)
    )


@pytest.mark.parametrize("schema", list(SCHEMAS))
def test_every_live_table_is_mapped(schema: str) -> None:
    """A new table without a model is invisible to application code."""
    insp = sa.inspect(_engine())
    live = set(_live_tables(insp, schema))
    mapped = set(_mapped_tables(schema))

    missing = sorted(live - mapped)
    assert not missing, (
        f"{schema}: {len(missing)} table(s) exist in the database but have no ORM "
        f"model: {missing}. Run `python scripts/generate_orm_models.py`."
    )


@pytest.mark.parametrize("schema", list(SCHEMAS))
def test_no_model_references_a_dropped_table(schema: str) -> None:
    """A model for a table that no longer exists fails only when first queried."""
    insp = sa.inspect(_engine())
    live = set(_live_tables(insp, schema))
    mapped = set(_mapped_tables(schema))

    stale = sorted(mapped - live)
    assert not stale, (
        f"{schema}: {len(stale)} model(s) reference tables that no longer exist: "
        f"{stale}. Run `python scripts/generate_orm_models.py`."
    )


@pytest.mark.parametrize("schema", list(SCHEMAS))
def test_columns_match(schema: str) -> None:
    """Column names must match exactly, in both directions.

    A missing column is a latent UndefinedColumn; an extra one is a column the
    application cannot see and will never use.
    """
    insp = sa.inspect(_engine())
    problems: list[str] = []

    for table_name, table in sorted(_mapped_tables(schema).items()):
        if table_name not in set(_live_tables(insp, schema)):
            continue  # covered by the stale-model test

        live_cols = {c["name"] for c in insp.get_columns(table_name, schema=schema)}
        mapped_cols = {c.name for c in table.columns}

        for col in sorted(live_cols - mapped_cols):
            problems.append(f"{table_name}.{col} in database but not in the model")
        for col in sorted(mapped_cols - live_cols):
            problems.append(f"{table_name}.{col} in the model but not in the database")

    assert not problems, (
        f"{schema}: {len(problems)} column mismatch(es):\n  "
        + "\n  ".join(problems)
        + "\nRun `python scripts/generate_orm_models.py`."
    )


@pytest.mark.parametrize("schema", list(SCHEMAS))
def test_nullability_matches(schema: str) -> None:
    """Nullability drives the Optional[...] annotations callers rely on."""
    insp = sa.inspect(_engine())
    problems: list[str] = []

    for table_name, table in sorted(_mapped_tables(schema).items()):
        if table_name not in set(_live_tables(insp, schema)):
            continue

        live = {c["name"]: bool(c["nullable"]) for c in insp.get_columns(table_name, schema=schema)}
        for col in table.columns:
            if col.name not in live:
                continue  # covered by the column test
            # Primary keys are implicitly NOT NULL and the generator omits the
            # explicit flag, so SQLAlchemy already reports them as non-nullable.
            if bool(col.nullable) != live[col.name]:
                problems.append(
                    f"{table_name}.{col.name}: model nullable={col.nullable}, "
                    f"database nullable={live[col.name]}"
                )

    assert not problems, (
        f"{schema}: {len(problems)} nullability mismatch(es):\n  "
        + "\n  ".join(problems)
        + "\nRun `python scripts/generate_orm_models.py`."
    )


def test_fact_models_are_not_re_exported() -> None:
    """Fact models must stay out of the convenient import path.

    The base fact tables carry money columns. sql_validator_agent blocks
    base-table access for GENERATED SQL, but it never sees hand-written ORM
    queries -- so an easy `AggSalesDaily.gross_sales_amount` import used to
    sidestep the HOD/EXEC split entirely. Since revision 20260828_09 neither read
    role holds a privilege on those tables, so it fails with "permission denied"
    instead; keeping the models out of the convenient import path keeps it from
    being a runtime surprise at all.

    Importing from app.models.schemas.v3_core directly is still allowed; this only
    keeps it from being the path of least resistance.
    """
    import app.models.schemas as schemas

    fact_models = [
        name
        for name in v3_core.__all__
        if name.startswith(("Fact", "Agg", "Bridge"))
    ]
    assert fact_models, "expected some fact models in v3_core"

    leaked = [name for name in fact_models if name in (schemas.__all__ or [])]
    assert not leaked, (
        f"fact model(s) re-exported from app.models.schemas: {leaked}. Keep them in "
        "v3_core only -- see the comment in app/models/schemas/__init__.py."
    )
