from __future__ import annotations

from app.db.postgres import Base

# Dimensions and metadata -- the tables application code actually queries.
from app.models.schemas.v3_core import (
    DimOpco,
    DimProduct,
    DimProductCategory,
    DimStore,
)
from app.models.schemas.v3_meta import (
    CopilotAccessLog,
    CopilotGlossary,
    CopilotLookupValue,
    MetricDefinition,
)

# ORM models for the v3 serving schema, generated by reflecting the live database:
#
#     python scripts/generate_orm_models.py
#
# Three rules make this safe to keep alongside explicit-SQL migrations.
#
# 1. The alembic revisions are the ONLY source of truth for DDL. `alembic
#    autogenerate` is NOT used, because partitioned parents, owner-executed
#    views and per-role grants have no declarative representation -- autogenerate
#    would emit migrations that drop them.
#
# 2. tests/test_schema_drift.py reflects the live database and diffs it against
#    this metadata, so models falling out of step is a failing test rather than a
#    silent runtime error on a rarely-touched column.
#
# 3. FACT MODELS ARE NOT RE-EXPORTED HERE. They exist in v3_core (accurate, and
#    useful as documentation) but must be imported from it explicitly.
#
#    The reason is narrow and specific: the base fact tables carry money columns,
#    and an ORM query never passes through sql_validator_agent. Generated SQL is
#    checked twice over -- the validator rejects every base-table name, and since
#    revision 20260828_09 neither read role holds any privilege on those tables --
#    but `select(func.sum(AggSalesDaily.gross_sales_amount))` inside copilot_scope
#    is hand-written code that skips the first check.
#
#    It now fails on the second: the query raises "permission denied for table
#    fact_sales_daily" whichever persona the caller is. That is a much better
#    outcome than the silent revenue read this note used to describe, and it is
#    still an error nobody wants to debug at runtime. Keeping the fact models out
#    of the convenient import path costs nothing and removes the easy mistake. If
#    you genuinely need one, import it directly and query it through
#    system_scope(), which runs as the loader.
#
# Partition children are not mapped: 160 classes with the same shape as their
# parents. Query the parent; PostgreSQL routes to the right partition.
#
# The ci_hod / ci_exec persona views are not mapped either. Their shape differs by
# role -- money columns are absent from ci_exec -- so one class cannot describe
# both, and the copilot reaches them through generated SQL resolved by search_path.

__all__ = [
    "Base",
    # ci_core dimensions
    "DimOpco",
    "DimProduct",
    "DimProductCategory",
    "DimStore",
    # ci_meta
    "CopilotAccessLog",
    "CopilotGlossary",
    "CopilotLookupValue",
    "MetricDefinition",
]
